FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["GestionTorneosDeportivos.Modelos.csproj", "./"]
RUN dotnet restore "GestionTorneosDeportivos.Modelos.csproj"
COPY . .
RUN dotnet build "GestionTorneosDeportivos.Modelos.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GestionTorneosDeportivos.Modelos.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GestionTorneosDeportivos.Modelos.dll"]